# basic options
title: deveb
author: Volkan TAŞ
email: belirtilmemiş@e-posta.yeradı
description: Yalnızca HTML, yalnızca CSS yeter. Çeviklik, çabukluk, yeğnilik, kolaylık ve dahasını barındıran bir çatı.
twitter_username: datadeveb
github_username:  data-deveb

# Build settings
highlighter: true
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# theme: minima

encoding: UTF-8

kategori-syrasy:
 - Başlangıç
 - Döşenek Düzeni

collections_dir: collections
collections:
  kylavuz:
    output: true
    permalink: /:name
  # kylavuz1:
  #   output: true
  #   permalink: /1.0/:name # (işlemiyor)


lsi: false
safe: true
source: 
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
